feat(azure): add more logic and logs to agent side watcher

diff --git a/ansible/roles/watcher/tasks/azure.yml b/ansible/roles/watcher/tasks/azure.yml
--- a/ansible/roles/watcher/tasks/azure.yml
+++ b/ansible/roles/watcher/tasks/azure.yml
@@ -19,7 +19,8 @@
     set -o pipefail
 
     # Variables
-    desired_capacity={{ watcher_desired_capacity }}
+    desired_capacity_cc={{ watcher_desired_capacity }}
+    start_scheduler="start"
 
     # Get metadata
     resource_group=$(curl -s -H "Metadata: true" --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-12-13" \
@@ -28,20 +29,56 @@
     # Authenticate
     az login --identity
 
-    # Update autoscaler
+    # Check if scaling is required
     autoscale_name=$(az monitor autoscale list --resource-group "${resource_group}" --query "[].name" --output tsv)
+
     start_profile=$(az monitor autoscale profile list \
       --autoscale-name "${autoscale_name}" \
       --resource-group "${resource_group}" \
-      --query "[?contains(name,'start')].name" \
+      --query "[?contains(name,'${start_scheduler}')].name" \
       --output tsv)
 
+    desired_capacity_current=$(az monitor autoscale profile list \
+      --autoscale-name "${autoscale_name}" \
+      --resource-group "${resource_group}" \
+      --query "[?contains(name,'${start_scheduler}')].capacity.default" \
+      --output tsv)
+
+    scaling_drift="${desired_capacity_current} --> ${desired_capacity_cc}"
+
+    if [[ -n "${desired_capacity_current}" ]]; then
+      if [[ ${desired_capacity_current} -eq ${desired_capacity_cc} ]]; then
+        echo "Skip scaling agent instances: ${scaling_drift}"
+        exit 0
+      fi
+    fi
+
+    # Update autoscaler
     az monitor autoscale update \
       --name "${autoscale_name}" \
       --resource-group "${resource_group}" \
-      --set 'profiles[name="'${start_profile}'"].capacity.default="'${desired_capacity}'"' \
-      --set 'profiles[name="'${start_profile}'"].capacity.maximum="'${desired_capacity}'"' \
-      --set 'profiles[name="'${start_profile}'"].capacity.minimum="'${desired_capacity}'"'
+      --set 'profiles[name="'${start_profile}'"].capacity.default="'${desired_capacity_cc}'"' \
+      --set 'profiles[name="'${start_profile}'"].capacity.maximum="'${desired_capacity_cc}'"' \
+      --set 'profiles[name="'${start_profile}'"].capacity.minimum="'${desired_capacity_cc}'"'
+
+    # Check scaling status
+    if [[ $? -eq 0 ]]; then
+      echo "Scaling agent instances successful: ${scaling_drift}"
+    else
+      echo "Scaling agent instances failed: ${scaling_drift}"
+    fi
   args:
     executable: bash
+  register: watcher_autoscaler
   changed_when: false
+
+- name: Show autoscaler output
+  ansible.builtin.debug:
+    msg: |
+      {{ item }}:
+      {% for out in item | extract(watcher_autoscaler) %}
+      {{ out }}
+      {% endfor %}
+  loop:
+    - stdout_lines
+    - stderr_lines
